using NuGroom.Nuget;

using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace NuGroom.Reporting
{
	/// <summary>
	/// Exports scanned package references as an SPDX 3.0.0 JSON-LD
	/// Software Bill of Materials (SBOM) document.
	/// </summary>
	internal static class SpdxSbomExporter
	{
		private const string SpdxVersion     = "3.0.0";
		private const string ContextUrl      = "https://spdx.org/rdf/3.0.0/spdx-context.jsonld";
		private const string CreatorToolName = "NuGroom";

		/// <summary>
		/// Writes an SPDX 3.0.0 JSON-LD file that catalogues every
		/// <see cref="PackageReferenceExtractor.PackageReference"/> as an
		/// <c>software_Package</c> element.
		/// </summary>
		/// <param name="references">Package references produced by a scan.</param>
		/// <param name="path">Destination file path for the SBOM.</param>
		public static void Export(
			IEnumerable<PackageReferenceExtractor.PackageReference> references,
			string path)
		{
			ArgumentNullException.ThrowIfNull(references);

			if (string.IsNullOrWhiteSpace(path))
			{
				throw new ArgumentException("Export path must not be empty.", nameof(path));
			}

			var createdUtc   = DateTimeOffset.UtcNow;
			var toolVersion  = Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "0.0.0";
			var documentId   = $"urn:spdx:nugroom-sbom-{createdUtc:yyyyMMddHHmmss}";
			var creationInfo = BuildCreationInfo(createdUtc, toolVersion);

			var graph = new List<object>();

			var packageElements = new List<string>();

			var uniqueReferences = references.DistinctBy(r => new { r.PackageName, r.Version });

			foreach (var r in uniqueReferences)
			{
				var element = BuildPackageElement(r, creationInfo);
				graph.Add(element);
				packageElements.Add(element.SpdxId);
			}

			var document = BuildDocumentElement(documentId, creationInfo, packageElements);
			graph.Insert(0, document);

			var root = new SpdxRoot
			{
				Context = ContextUrl,
				Graph   = graph
			};

			var options = new JsonSerializerOptions
			{
				WriteIndented                          = true,
				DefaultIgnoreCondition                 = JsonIgnoreCondition.WhenWritingNull,
				PropertyNamingPolicy                   = JsonNamingPolicy.CamelCase,
				Encoder                                = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
			};

			var json = JsonSerializer.Serialize(root, options);
			File.WriteAllText(path, json, Encoding.UTF8);
		}

		private static SpdxCreationInfo BuildCreationInfo(DateTimeOffset created, string toolVersion)
		{
			return new SpdxCreationInfo
			{
				SpecVersion = SpdxVersion,
				Created     = created.ToString("yyyy-MM-ddTHH:mm:ssZ"),
				CreatedBy   = [$"{CreatorToolName}-{toolVersion}"],
				Comment     = "Generated by NuGroom package scanner"
			};
		}

		private static SpdxDocument BuildDocumentElement(
			string documentId,
			SpdxCreationInfo creationInfo,
			List<string> rootElementIds)
		{
			return new SpdxDocument
			{
				Type         = "SpdxDocument",
				SpdxId       = documentId,
				Name         = "NuGroom SBOM",
				CreationInfo = creationInfo,
				RootElement  = rootElementIds
			};
		}

		private static SpdxPackage BuildPackageElement(
			PackageReferenceExtractor.PackageReference reference,
			SpdxCreationInfo creationInfo)
		{
			var info     = reference.NuGetInfo;
			var purls    = BuildPackageUrl(reference.PackageName, reference.Version);
			var spdxId   = $"urn:spdx:pkg-{SanitizeId(reference.PackageName)}-{SanitizeId(reference.Version ?? "unspecified")}";

			return new SpdxPackage
			{
				Type            = "software_Package",
				SpdxId          = spdxId,
				Name            = reference.PackageName,
				PackageVersion  = reference.Version,
				CreationInfo    = creationInfo,
				DownloadLocation = info?.PackageUrl ?? "https://www.nuget.org/packages/" + reference.PackageName,
				Description     = info?.Description,
				Homepage        = info?.ProjectUrl,
				ExternalIdentifier = purls != null
					? [new SpdxExternalIdentifier { ExternalIdentifierType = "purl", Identifier = purls }]
					: null,
				OriginatedBy    = info?.Authors != null ? [info.Authors] : null,
				SuppliedBy      = info?.Authors,
				CopyrightText   = "NOASSERTION",
				SecurityInfo    = BuildSecurityInfo(info)
			};
		}

		private static SpdxSecurityInfo? BuildSecurityInfo(NuGetPackageResolver.PackageInfo? info)
		{
			if (info == null)
			{
				return null;
			}

			if (!info.IsDeprecated && !info.IsVulnerable)
			{
				return null;
			}

			return new SpdxSecurityInfo
			{
				IsDeprecated  = info.IsDeprecated ? true : null,
				IsVulnerable  = info.IsVulnerable ? true : null,
				Advisories    = info.Vulnerabilities?.Count > 0 ? info.Vulnerabilities : null
			};
		}

		private static string? BuildPackageUrl(string packageName, string? version)
		{
			if (string.IsNullOrWhiteSpace(version))
			{
				return $"pkg:nuget/{packageName}";
			}

			return $"pkg:nuget/{packageName}@{version}";
		}

		private static string SanitizeId(string value)
		{
			var chars = value.Select(c => char.IsLetterOrDigit(c) || c == '.' || c == '-' ? c : '-').ToArray();
			return new string(chars);
		}

		#region SPDX 3.0.0 DTOs

		private sealed class SpdxRoot
		{
			[JsonPropertyName("@context")]
			public string Context { get; set; } = default!;

			[JsonPropertyName("@graph")]
			public List<object> Graph { get; set; } = [];
		}

		private sealed class SpdxCreationInfo
		{
			public string SpecVersion { get; set; } = default!;
			public string Created { get; set; }     = default!;
			public List<string> CreatedBy { get; set; } = [];
			public string? Comment { get; set; }
		}

		private sealed class SpdxDocument
		{
			public string Type { get; set; }         = default!;
			public string SpdxId { get; set; }       = default!;
			public string Name { get; set; }         = default!;
			public SpdxCreationInfo CreationInfo { get; set; } = default!;
			public List<string> RootElement { get; set; }      = [];
		}

		private sealed class SpdxPackage
		{
			public string Type { get; set; }            = default!;
			public string SpdxId { get; set; }          = default!;
			public string Name { get; set; }            = default!;
			public string? PackageVersion { get; set; }
			public SpdxCreationInfo CreationInfo { get; set; }    = default!;
			public string? DownloadLocation { get; set; }
			public string? Description { get; set; }
			public string? Homepage { get; set; }
			public List<SpdxExternalIdentifier>? ExternalIdentifier { get; set; }
			public List<string>? OriginatedBy { get; set; }
			public string? SuppliedBy { get; set; }
			public string? CopyrightText { get; set; }
			public SpdxSecurityInfo? SecurityInfo { get; set; }
		}

		private sealed class SpdxExternalIdentifier
		{
			public string ExternalIdentifierType { get; set; } = default!;
			public string Identifier { get; set; }             = default!;
		}

		private sealed class SpdxSecurityInfo
		{
			public bool? IsDeprecated { get; set; }
			public bool? IsVulnerable { get; set; }
			public List<string>? Advisories { get; set; }
		}

		#endregion
	}
}
